### ISSUE TITLE
A tab or section for the an overview per wiki

### ISSUE THREAD

**Issue by samuelguebo** [samuelguebo/consultation-stats#1]
A tab or section to get an overview per wiki: so many from this wiki, so many from this. It’s a bit difficult to see in the circle, except you immediately see the English dominance. More of a list of wikis: English, 62%, so many users. Second wiki, so many %, so many users.

**Comment by acagastya** [comment]
Do you want that to be below the results table as a "Summary" section?

**Comment by acagastya** [comment]
@samuelguebo I am thinking of a way to implement this -- can you tell me when does the data fetching for results finish?

**Comment by acagastya** [comment]
<img width="1126" alt="Screenshot 2020-10-06 at 23 27 38" src="https://user-images.githubusercontent.com/5466083/95241545-869d3e00-082b-11eb-97e9-a64794619e11.png">
Does this look all right?  Would you like to have any more columns?

**Comment by samuelguebo** [comment]
> @samuelguebo I am thinking of a way to implement this -- can you tell me when does the data fetching for results finish?

Hey, the fetching is done in parallel. What you could do instead of waiting for all the fetching to finish is to update the summary table as you pull the data, using database names as `id` attribute to identify the rows. Actually, it is how the the chart is updated: whenever one of the parallel requests is complete. Let me know if the snippet below is useful

https://github.com/samuelguebo/consultation-stats/blob/7f74389d53f403577a760fc7136aecae44f268d8/js/wiki-repository.js#L98-L113

**Comment by samuelguebo** [comment]
> Do you want that to be below the results table as a "Summary" section?

Yes bellow would be excellent. Once it is done can add some links at the top so that people can scroll down to it directly alongside a batck-to-top button.

**Comment by acagastya** [comment]
@samuelguebo Oh, I used the global variable `list` for doing that work.  ~~However, adding a second table breaks the sorting of both the tables.  I am guessing the sorting was implemented thinking there is only one table on the page.  Could you modify that, please?~~ < that was an issue at my end -- I think I have resolved that.

**Comment by acagastya** [comment]
#16 adds this functionality.  ~~But problems of #17 persists.~~
It also solves #17.

**Comment by samuelguebo** [comment]
Impressive work as well!

**Comment by acagastya** [comment]
Thanks, @samuelguebo.

I think we can close this now.  :D
