### ISSUE TITLE
[discussion] Which wiki's advanced rights to show?

### ISSUE THREAD

**Issue by acagastya** [samuelguebo/consultation-stats#13]
I had been using the tool, trying out on my primary wiki (enwikinews) and for the parameter `?wiki=en.wikinews.org&page=Neuroscientists+tell+Wikinews+about+empathy+and+harm+aversion+observed+in+lab+rats`, I noticed something odd.

<img width="1440" alt="Screenshot 2020-10-06 at 18 59 36" src="https://user-images.githubusercontent.com/5466083/95207956-17f9b980-0806-11eb-9ad6-02c2511bad1b.png">
That article was edited by four sysops: Bddpaux, Pi zero, Green Giant and me (acagastya).  However, currently Advanced rights column shows rights of the "home wiki".  I don't think that is being helpful.

For example, I am looking for a page on **enwikinews** and Pi zero, who is the most active admin will never be shown as sysop as their home wiki is enwp.  Ixfd64, who is not currently a sysop on enwn will have sysop next to their name because their home wiki is enwp.

I think the "advanced rights" should reflect rights on that particular wiki; as rights are based on the individual's involvement with different projects, not their home wiki.  Take my case for example -- I created my account on enwp but I have stopped editing Wikipedia.  I have certain advanced rights on commons and wikinews and I think those are being more informative based on the projects the user is searching for.

Sorting the table based on advanced rights on home wiki would not convey an easy-to-grasp idea.  "An enwn page is edited by sysops of enwp, enwn, and commons" -- that information is not easy to use.  On the other hand, if a page was edited by four sysops of that wikiproject -- that gives a clear cut idea.  Don't you think?

What do you think advanced rights column should show?  And why?

**Comment by tacsipacsi** [comment]
I agree that rights on the current wiki (i.e. enwikinews in this example) are relevant, but IMO the home wiki’s/any other wiki’s rights are also relevant, as that tells a lot about the user’s experience and acceptance within the community (even though there’s no direct connection between the two, as experienced and accepted users may not have rights if they simply don’t want them).

**Comment by samuelguebo** [comment]
Hey @tacsipacsi and @acagastya, thanks for stopping here folks and sharing your feedback. Truly appreciate.
Is my understanding correct that you suggest that all ([relevant rights](https://github.com/samuelguebo/consultation-stats/blob/a79f177c85bffd18a062b3a69bdc9fc4cde38a7c/js/wiki-repository.js#L141-L142)) that the user possess on all wikis should be, instead of just their rights on their homewiki?

**Comment by tacsipacsi** [comment]
In my understanding all rights should be shown, but not equally: I think the most useful would be to show an “advanced rights on current wiki” and an “advanced rights on other wikis” column. Global rights should probably appear in both.

**Comment by acagastya** [comment]
@samuelguebo I meant, if you are looking at, say `enwikibooks` -- the advanced rights of all the users in the table should be on `enwikibooks` only.  If someone had created their account on `zhwikivoyage` but they moved to editing other projects, it would be pointless to list the user's `zhwikivoyage` rights when we are looking for a page on `enwikibooks`.

Similarly, showing all advanced rights on different projects as @tacsipacsi has suggested -- all rights from all wikis should be shown because it ‘tells a lot about the user’s experience and acceptance within the community’.  
However, think about it -- for `User:JohnDoe`, if their advanced rights column for other wikis does not show `sysop` on `arwikiquotes` -- that does not tell us if they aren't a `sysop` on `arwikiquotes` or if they don't even edit `arwikiquotes`.

**Comment by acagastya** [comment]
On a side note, there are rights such as `reviewer` which are relevant on `enwikibooks` and `enwikinews` (if I recall correctly, `dewikipedia` too) and rights such as `file mover` `image reviewer` which are important on `commons`.  Should we add those to `relevant rights` (https://github.com/samuelguebo/consultation-stats/blob/a79f177c85bffd18a062b3a69bdc9fc4cde38a7c/js/wiki-repository.js#L141)?

**Comment by tacsipacsi** [comment]
Yes, the [FlaggedRevs](https://www.mediawiki.org/wiki/Extension:FlaggedRevs) right is important, used on [quite a number of wikis](https://github.com/wikimedia/operations-mediawiki-config/blob/master/dblists/flaggedrevs.dblist). However, pay attention that its internal name is `editor`, not `reviewer`. Similarly, the Commons rights are `filemover` and `image-reviewer`, respectively.

**Comment by samuelguebo** [comment]
That sounds reasonable to me. I would be cautious about the risk of flooding the table with too many details. If a lot of users have many rights, it could make the table cumbersome. A second point is a suggestion to sort the relevantGroups and global groups arrays either alphabetically or by scope eg: `[ 'stewards', 'staff', 'checkuser', 'oversighter', 'otrs members', 'sysop' ]`

**Comment by acagastya** [comment]
Okay, will implement shortly.
