### ISSUE TITLE
Compatibility with old browsers + code formatting

### ISSUE THREAD

**Issue by acagastya** [samuelguebo/consultation-stats#14]
There are two important housekeeping activities one should do -- the sooner the better.

The first being compatibility -- the current JavaScript source code benefits from post ES5 syntax such as arrow function expression ( `=>` ), `async`-`await`, `Promise`s, spread operator (`...`), `let`/`const` et cetera.  These won't work in the older browsers.  I strongly suggest the modern JavaScript should be transpiled to ES5 (or ES3) syntax so people using older browsers can use it too.  TypeScript compiler or babel -- either can be used to automate this.

Code formatting -- at various places semi-colon was used, at times it was not.  It would be useful to stick to a standard.  Same with double/single quotes and other such things.

What do you think, @samuelguebo?

**Comment by samuelguebo** [comment]
@acagastya, those are valid concerns. For the double/single quotes. Using single quotes and semi-colon makes sense. I think settings some stricter rules in my linter could have helped with that a bit.

As for the backward compatibility, I have to admit that I was a bit reluctant to bringing the whole npm army and its packages for transpiling and so on. However, as the tool is gaining for attention, I think it is fair to consider those options as well. I am fine leveraging babel — not super familiar with TypeScript but giving it a try won't kill for sure.

**Comment by tacsipacsi** [comment]
When I met TypeScript, I immediately fell in love with it—it’s the same well-known JavaScript, but with static typing added. This is good for safety and scalability (static typing points out when you do something wrong, without any thorough testing), and also for tooling: VS Code’s IntelliSense is much more helpful when it knows the types of the variables. If you don’t want to work through the whole code base now, you can simply say that all your JS code is TS—it is, TS is a superset of JS. This way you can gradually shift to TS, and you can enjoy its improvements from the first moment.

**Comment by samuelguebo** [comment]
It's hard to say no to such as nicely crafted pitch about TS 😄  I'm in!

**Comment by acagastya** [comment]
@samuelguebo I had implemented formatting and transpiling on my fork here https://github.com/acagastya/consultation-stats/commit/a4d81311d097f891b4967fed29ab553117522128 -- prettier and typescript both get the work done nicely.  I will add the PRs that were added to this repo last night, then submit a PR, if that is okay.

**Comment by acagastya** [comment]
Also, @samuelguebo, the formatting should be standard across different contributors.  This commit https://github.com/samuelguebo/consultation-stats/commit/0f34a44a917e2ebfac53ede0155be77a3cb26e32 will not work as we expect if contributors have prettier installed, or have custom prettier configuration., or if they do not have ESLint, or in my case: they use vim.  I would say leave `.vscode` in `.gitignore` file, and add a `.prettierrc` configuration like this https://github.com/acagastya/consultation-stats/blob/a4d81311d097f891b4967fed29ab553117522128/.prettierrc

**Comment by samuelguebo** [comment]
> Also, @samuelguebo, the formatting should be standard across different contributors. This commit [0f34a44](https://github.com/samuelguebo/consultation-stats/commit/0f34a44a917e2ebfac53ede0155be77a3cb26e32) will not work as we expect if contributors have prettier installed, or have custom prettier configuration., or if they do not have ESLint, or in my case: they use vim. I would say leave `.vscode` in `.gitignore` file, and add a `.prettierrc` configuration like this https://github.com/acagastya/consultation-stats/blob/a4d81311d097f891b4967fed29ab553117522128/.prettierrc

I see what you mean. I'll stick to this newly crafted version.
