### ISSUE TITLE
TypeError on API error

### ISSUE THREAD

**Issue by tacsipacsi** [samuelguebo/consultation-stats#4]
### Steps to reproduce
1. Open https://consultation-stats.toolforge.org/?wiki=hu.wikipedia.org&page=Wikip%C3%A9dia%3AKocsmafal+%28egy%C3%A9b%29 and open your browser console.
2. Wait. A lot. This is a pretty big page with huge edit history, sorry for not finding a smaller one. (Maybe you should create a server-side component that queries the database directly and returns all the data for one single GET request instead of issuing tons of API calls.)
3. Notice the error `TypeError: data.query is undefined` occurring in line 127 of [wiki-repository.js](https://github.com/samuelguebo/consultation-stats/blob/e05ae83/js/wiki-repository.js). I got this while processing the result of https://hu.wikipedia.org/w/api.php?action=query&meta=globaluserinfo&format=json&guiuser=213.197.76.168&origin=*&guiprop=groups.

### Comments
I see that it’s in a `try` block, but within that block it’s in a callback function, so the try-catch doesn’t apply. Since you `await` the result anyway, maybe the easiest is to `await` just the `fetch` call and process everything in the main function’s body instead of using callbacks (here and everywhere else in the file). Of course, you can also simply skip getting errors by not querying global groups for IPs… But you should either make use of the `try` or remove it either way.

**Comment by samuelguebo** [comment]
Hello @tacsipacsi, that's a great feedback, thank you.  Yeah ideally, an alternate branch should be created with a version that can use SQL dumps to minimize HTTP request. I've mentioned this in an earlier discussion https://github.com/samuelguebo/consultation-stats/issues/3. 

For now I got rid of the redundant try/catch blocks and improved the loading time by getting rid of some await/async (Cf. b75a87ea8ced77e1d23eb96524bf9c0bffb39578). You may want to give it a try again after clearing your cache: https://consultation-stats.toolforge.org/?wiki=hu.wikipedia.org&page=Wikip%C3%A9dia%3AKocsmafal+%28egy%C3%A9b%29

**Comment by tacsipacsi** [comment]
It still errors out, although the problematic line is `#147` now. You could test whether `data.error` is an object (not `undefined`), and not take any step further if it is.

**Comment by samuelguebo** [comment]
@tacsipacsi, I wasn't able to see the error but I've followed the advice of checking for `data.error` and exiting in https://github.com/samuelguebo/consultation-stats/commit/9a5e23a002738f65bbcebddec8b08ba6f5c4f5a0. Feel free to submit a PR if you're still able to experience the error, and I'll be happy to merge.

**Comment by tacsipacsi** [comment]
(Sorry for the late response.) Now I don’t see any errors. Probably you looked at the browser console? Maybe that doesn’t show the exception; it’s set to display all XHR requests for me, so it’s completely unusable on this page anyway. I have Firefox set to automatically break on uncaught exceptions (Debugger tab), and that was where noticed the exception.
