### ISSUE TITLE
Switch from API calls to SQL queries

### ISSUE THREAD

**Issue by samuelguebo** [samuelguebo/consultation-stats#5]
**Issue**
The product relies on HTTP queries and the higher the number of participant in a discussions the large the number of queries. While this is fine with relatively small conversations, it can lead to large consumption of server resources when dealing with discussions that have thousands of participants. In other words, the more the participants, the likelier we are to get errors such as `too many queries` or inconsistent numbers. 

**Solution**
Use database [dumps hosted on ToolForge](https://wikitech.wikimedia.org/wiki/Help:Toolforge/Database#Connecting_to_the_database_replicas) instead and rely on `JOIN`s to collect relevant pieces of information.

**Comment by samuelguebo** [comment]
@acagastya, just a heads-up that I'll start a separate branch that will comprise of a lightweight backend that interacts with the database and exposes the data through some endpoints. You may want to delay any major change to the code base for the next 24 hours, just in case we end up using that branch instead.

Happy to hear your thoughts on this as well.

**Comment by samuelguebo** [comment]
**Update**: @acagastya and @tacsipacsi the branch is live here with a basic routing mechanism and some controllers. The controller methods aren't fully implemented yet, especially for the syncing with the database. You can see the branch here: https://github.com/samuelguebo/consultation-stats/commits/sql-powered

Will try to complete some of the SQL queries and do some tests on production tomorrow as I am not sure whether I can connect to ToolForge's database from localhost — let me know if you folks have recommendations.

**Comment by acagastya** [comment]
This may not be the most efficient method, but for starters, one could move the `fetch` requests on the NodeJS backend -- without needing major rewrites.

**Comment by samuelguebo** [comment]
Hey @acagastya and @tacsipacsi, I'm making some progress on the backend enpoints as it now  `/users` spits out replica's data as you can see here with the first parameter being the `wikiDb` and the second the `pageId`: https://consultation-stats.toolforge.org/users/metawiki_p/11113472

I'm yet to figure how to get central_auth data such as `homewiki`, `registration date`, and `global rights`. Will keep examining the databases structures but I'm welcoming any ideas you guys may have. The current SQL looks like this https://github.com/samuelguebo/consultation-stats/blob/b5c2a1134c2039fd2a8febdd9238278d565357f6/app/controllers/users.js#L39-L50

**Comment by samuelguebo** [comment]
Abandoning this idea. Per discussions with a DBA, replicas do not appear to be tailored for that sort of heavy computation. For now, sticking with API calls, as APIs handle caching pretty well.
